### ISSUE TITLE
Incompatible with Wordpress 5.5

### ISSUE THREAD

**Issue by videoMonkey** [OnTheGoSystems/toolset-dynamic-sources#8]
I was trying to create a vimeo block with dynamic source and this is the error that this module generates with WP 5.5.1. I tried linking the library from the toolset-blocks plugin, it doesn't have this error, but I get webpack errors that I don't understand. 

`[11-Sep-2020 09:03:24 UTC] PHP Notice:  register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>toolset-dynamic-sources/v1/dynamic-sources</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.) in /Users/jamie/Local Sites/test/app/public/wp-includes/functions.php on line 5225`

**Comment by kmgalanakis** [comment]
@videoMonkey sorry for the late reply.

Since you created your issue, the repo has been updated with the latest version of the API.

Also, at the moment we are preparing a new version that makes the integration even easier so the documentation will be updated as well. Note that the current version of the documentation is not really relevant anymore so you might have issues following it.

Let me know if you have issues trying to integrate the API into your plugin while the documentation is not updated, so that I can help you move forward.

Thank you.
